# Generated by Django 5.2.7 on 2025-12-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioadaptado',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='usuarioadaptado',
            name='nome_bairro',
        ),
        migrations.RemoveField(
            model_name='usuarioadaptado',
            name='nome_cidade',
        ),
        migrations.RemoveField(
            model_name='usuarioadaptado',
            name='nome_mae',
        ),
    ]
