# Generated by Django 5.2.6 on 2025-09-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_retirante', models.CharField(max_length=100)),
                ('cpf_retirante', models.CharField(max_length=100)),
                ('data_devolucao', models.DateField()),
                ('objeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucao', to='objetos.objeto')),
            ],
        ),
    ]
