# Generated by Django 5.2.6 on 2025-09-13 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0003_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos', to='objetos.categoria'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Devolução'), ('devolvido', 'Devolvido')], default='aguardando', max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='cpf_retirante',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='data_achado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='descricao',
            field=models.TextField(),
        ),
    ]
