# Generated by Django 5.2.7 on 2025-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0005_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='objetos_fotos/'),
        ),
    ]
