# Generated by Django 5.2.7 on 2025-11-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0006_objeto_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devolucao',
            old_name='cpf_retirante',
            new_name='cpf_resgate',
        ),
        migrations.RenameField(
            model_name='devolucao',
            old_name='nome_retirante',
            new_name='nome_resgate',
        ),
    ]
